apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: httpbin-routes
  namespace: gloo-system
spec:
  routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
      # options:
      #   prefixRewrite: /
    