apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options: 
      # networkLocalRatelimit: 
      #   maxTokens: 1
      #   tokensPerFill: 1
      #   fillInterval: 100s
      #           # options:
      httpLocalRatelimit:
        defaultLimit:
          fillInterval: 3s
          maxTokens: 500
          tokensPerFill: 300
        enableXRatelimitHeaders: true
  ssl: false
  useProxyProto: false